version: 0.2
phases:
  install:
    commands:
      - echo "the installation phase begins"
      - cd client
      - npm install

  pre_build:
    commands:
      - echo "the prebuild phase begins"

  build:
    commands:
      - echo "the build phase begins"
      - npm run build

  post_build:
    commands:
      - echo "the post build phase. navigating back to root path"
      - cp -R build/ ../

artifacts:
  files:
    - build/**/*
    - appspec.yml
    - nginx/*
    - scripts/*
    - docker-compose.yaml
    - Dockerfile
